blank_issues_enabled: false
contact_links:
  - name: ❓ Questions
    url: https://github.com/A-Baer/LaraBeacon/discussions
    about: The issuer tracker is focused on reporting bugs or problems. Please use the Discussions tabs for questions!
  - name: 📚 Documentation improvements
    url: https://github.com/A-Baer/LaraBeacon/issues/new?template=---feature-request.md
    about: Suggest documentation improvements through the feature request template.
  - name: Security reports
    url: https://github.com/A-Baer/LaraBeacon/security/policy
    about: Please follow the private reporting instructions in our security policy.
